<script setup lang="ts">
// Draws a box's `qr:` URL as a QR code. The SVG is generated on demand (the
// encoder is a lazy chunk), so a slide without a QR pays nothing.
import { ref, watch } from 'vue'
import { qrSvg } from '../render/qr'

const props = defineProps<{ text: string; dark?: string; light?: string }>()

const svg = ref('')
const failed = ref(false)
// Renders race when the URL is edited quickly; only the newest result may win.
let token = 0

watch(
  () => [props.text, props.dark, props.light] as const,
  async ([text, dark, light]) => {
    const mine = ++token
    if (!text) {
      svg.value = ''
      failed.value = false
      return
    }
    try {
      const out = await qrSvg(text, dark, light)
      if (mine === token) {
        svg.value = out
        failed.value = false
      }
    } catch {
      if (mine === token) {
        svg.value = ''
        failed.value = true // encoder chunk unreachable, or the URL is too long
      }
    }
  },
  { immediate: true },
)
</script>

<template>
  <!-- The markup is generated by render/qr.ts from a colour and a module grid;
       the URL only ever enters the encoder, never the DOM as text. -->
  <div v-if="!failed" class="el-box-qr" v-html="svg" />
  <div v-else class="el-box-qr qr-failed" title="QR code could not be rendered">⚠</div>
</template>

<style scoped>
.el-box-qr {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
}
.el-box-qr :deep(svg) {
  width: 100%;
  height: 100%;
  display: block;
}
.qr-failed {
  color: rgba(230, 236, 242, 0.5);
  font-size: 24px;
}
</style>
