// The shipped tour (deck.example.md) is the first thing every visitor to the
// GitHub Pages demo sees, and it seeds every fresh install. It's generated by
// scripts/gen-example.mjs; this locks that it still parses cleanly against the
// current schema — a layout or field rename that the generator missed would
// otherwise only show up as a warning banner on someone else's screen.
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { parseDeck, serializeDeck } from './deck'
import { analyzeDeck } from './analyze'
import { chartData } from './chart'
import { cloudData } from './cloud'

const raw = readFileSync(resolve(__dirname, '../../deck.example.md'), 'utf8')
const deck = parseDeck(raw)

describe('the shipped example deck', () => {
  it('parses with no schema warnings', () => {
    const schema = analyzeDeck(deck).issues.filter((i) => i.kind === 'schema')
    expect(schema, JSON.stringify(schema, null, 2)).toEqual([])
  })

  it('round-trips through the serializer unchanged', () => {
    expect(parseDeck(serializeDeck(deck))).toEqual(deck)
  })

  it('shows off every table view, each with data to draw', () => {
    const tables = deck.slides.filter((s) => s.layout === 'table')
    const views = tables.map((s) => s.table?.view ?? 'table').sort()
    expect(views).toEqual(['cloud', 'pie', 'table'])
    const pie = tables.find((s) => s.table?.view === 'pie')!
    expect(chartData(pie.table).every((d) => d.value > 0)).toBe(true)
    const cloud = tables.find((s) => s.table?.view === 'cloud')!
    expect(cloudData(cloud.table).length).toBeGreaterThan(3)
  })

  it("charts the tour's own sections, so the pie can never be stale", () => {
    const pie = deck.slides.find((s) => s.table?.view === 'pie')!
    const counted = new Map(chartData(pie.table).map((d) => [d.label, d.value]))
    for (const [group, n] of counted) {
      expect(deck.slides.filter((s) => s.group === group)).toHaveLength(n)
    }
  })
})
